name: binary_image_generator
description: "A Flutter package to generate customizable 5x5 grid images based on a 15-bit binary string. Define background and square colors, and receive the generated image as a Uint8List for reuse or further processing. Uses efficient Canvas rendering for optimal performance, making it ideal for creating unique binary-pattern visuals in your app."
version: 0.0.1
homepage: "https://github.com/nadersakr/binary_image_generator"  # Add your package's homepage URL, or leave empty if you don't have one.

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
